//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_fundation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_fundation()
        {
            this.application1 = new HashSet<application>();
        }
    
        public int id { get; set; }
        public int application_Id { get; set; }
        public int fundation_Id { get; set; }
    
        public virtual application application { get; set; }
        public virtual foundation foundation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<application> application1 { get; set; }
    }
}
