//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int id { get; set; }
        public int user_Id { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public string main_place_of_work { get; set; }
        public string position_in_combination { get; set; }
        public string type { get; set; }
        public string purpose { get; set; }
        public string saving_salary { get; set; }
        public string trip_city { get; set; }
        public string trip_country { get; set; }
        public string institution { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string itinerary { get; set; }
        public Nullable<int> app_transport_Id { get; set; }
        public string payment { get; set; }
        public int app_fundation_Id { get; set; }
        public string institutionLocation { get; set; }
    
        public virtual app_fundation app_fundation { get; set; }
        public virtual app_transport app_transport { get; set; }
        public virtual user user { get; set; }
    }
}
