//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTrip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class businesstripEntities : DbContext
    {
        public businesstripEntities()
            : base("name=businesstripEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_fundation> app_fundation { get; set; }
        public virtual DbSet<app_transport> app_transport { get; set; }
        public virtual DbSet<application> application { get; set; }
        public virtual DbSet<foundation> foundation { get; set; }
        public virtual DbSet<institution> institution { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<purpose> purpose { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<saving_salary> saving_salary { get; set; }
        public virtual DbSet<transport> transport { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
